### ISSUE TITLE
HELP WANTED - How can I use your SynologyKit with SwiftUI

### ISSUE THREAD

**Issue by CPiersigilli** [alexiscn/SynologyKit#1]
I tried using your SynologyKit with SwiftUI without success: how can I do it?
How can I handle errors resulting from, for example, an incorrect host, or incorrect user, or incorrect password, or .... ?
I have tested your SynologyKitExample with DS918+ and is very very fast.
Thank you for your great SynologyKit.

**Comment by alexiscn** [comment]
You can referer [MovieSwiftUI](https://github.com/Dimillian/MovieSwiftUI)

API Related code is [here](https://github.com/Dimillian/MovieSwiftUI/blob/master/MovieSwift/MovieSwift/flux/actions/MoviesActions.swift)

SynologyKit document has updated.

**Comment by CPiersigilli** [comment]
Thanks, now I was able to get your SynologyKit working with SwiftUI.

If no connection, the error is:
<img width="230" alt="Schermata 2019-11-09 alle 19 04 19" src="https://user-images.githubusercontent.com/17962752/68532961-33252600-0324-11ea-9219-66871c036eab.png">
In this case the error is correct.

If I enter an incorrect URL:
<img width="230" alt="Schermata 2019-11-09 alle 18 53 05" src="https://user-images.githubusercontent.com/17962752/68532817-4636f680-0322-11ea-8296-750de27d5036.png">
In this case the error is correct.

But, with a wrong password or wrong user the error is:
<img width="229" alt="Schermata 2019-11-09 alle 18 59 38" src="https://user-images.githubusercontent.com/17962752/68532888-1f2cf480-0323-11ea-9ad8-c2dfc5899f92.png">
In this case the error is wrong, because the error is "No such account or incorrect password" with Id 400. 

How can I do to show the correct error?

**Comment by alexiscn** [comment]
I will fix it in later version...

**Comment by alexiscn** [comment]
> Thanks, now I was able to get your SynologyKit working with SwiftUI.
> 
> If no connection, the error is:
> <img alt="Schermata 2019-11-09 alle 19 04 19" width="230" src="https://user-images.githubusercontent.com/17962752/68532961-33252600-0324-11ea-9219-66871c036eab.png">
> In this case the error is correct.
> 
> If I enter an incorrect URL:
> <img alt="Schermata 2019-11-09 alle 18 53 05" width="230" src="https://user-images.githubusercontent.com/17962752/68532817-4636f680-0322-11ea-8296-750de27d5036.png">
> In this case the error is correct.
> 
> But, with a wrong password or wrong user the error is:
> <img alt="Schermata 2019-11-09 alle 18 59 38" width="229" src="https://user-images.githubusercontent.com/17962752/68532888-1f2cf480-0323-11ea-9ad8-c2dfc5899f92.png">
> In this case the error is wrong, because the error is "No such account or incorrect password" with Id 400.
> 
> How can I do to show the correct error?

Fixed in Version 0.2.5

**Comment by CPiersigilli** [comment]
Now work fine.
Thank you.
