### ISSUE TITLE
Package resolution failed.

### ISSUE THREAD

**Issue by CPiersigilli** [alexiscn/SynologyKit#2]
If I try to add package of you SynologyKit with "`Add Package Dependency...`" I have the error:
<img width="734" alt="Schermata 2019-11-10 alle 15 37 17" src="https://user-images.githubusercontent.com/17962752/68545926-029bc580-03d2-11ea-8a13-eb409bcaeefd.png">
Can you fix it?
Thank you.

**Comment by alexiscn** [comment]
I think it is CocoaPods Cache problem...

**Comment by CPiersigilli** [comment]
I'm not an expert on these issues, but I noticed that, for example, Alamofire contains a file called Package.swift ([click here](https://github.com/Alamofire/Alamofire/blob/master/Package.swift)), which is not present in your SynologyKit: could this be the problem?

**Comment by alexiscn** [comment]
> I'm not an expert on these issues, but I noticed that, for example, Alamofire contains a file called Package.swift ([click here](https://github.com/Alamofire/Alamofire/blob/master/Package.swift)), which is not present in your SynologyKit: could this be the problem?

Yes. Currently Synology Only Support CocoaPods. Maybe will support Swift Package later.

**Comment by alexiscn** [comment]
Please try again..

**Comment by CPiersigilli** [comment]
I tried, but below I show you the error.
<img width="735" alt="Schermata 2019-11-12 alle 21 37 27" src="https://user-images.githubusercontent.com/17962752/68708779-b6e54980-0594-11ea-96ad-28c301c715fe.png">

**Comment by alexiscn** [comment]
My bad. I forgot that 0.2.6 version does not contains Package.swift file.

Now fixed. Try 0.2.7 :D

**Comment by CPiersigilli** [comment]
Great. Now work fine.

**Comment by subayks** [comment]
Can anyone help me to fix this issue ?..i am using xcode 11 . i am getting same error "package resolution error "

Thanks in advance

**Comment by alexiscn** [comment]
Can you paste your error snapshot.

I created a new project using Xcode 11.4, and add `SynologyKit` as a package dependency.

![1585554648027](https://user-images.githubusercontent.com/1132546/77888409-cdb7de80-729e-11ea-9425-5803fb3bf2ec.jpg)

And after a few minutes. The package is successfully added.

![1585554909924](https://user-images.githubusercontent.com/1132546/77888489-f0e28e00-729e-11ea-9b69-d797a8fc5a73.jpg)

**Comment by subayks** [comment]
![
![IMG-20200330-WA0005](https://user-images.githubusercontent.com/32360429/77889350-53319380-728b-11ea-836d-e480e5d2e138.jpg)

**Comment by subayks** [comment]
![IMG-20200330-WA0004](https://user-images.githubusercontent.com/32360429/77889383-5fb5ec00-728b-11ea-8f30-4a8464c82954.jpg)

**Comment by subayks** [comment]
Hi alex,
Can i get your contact details ?
My mailId is Subay421@gmail.com

**Comment by alexiscn** [comment]
It seems you are not adding `SynologyKit` using SPM ?

swift-lambda-app seems can not resolved by Xcode SPM. But it has document for how to intergrate.

If you want to add swift-lambda-app as a swift package dependency. Then you should open an issue to swift-lambda-app.

**Comment by subayks** [comment]
Thanks 😄
