### ISSUE TITLE
HELP WANTED - How to set options in Upload method. 

### ISSUE THREAD

**Issue by CPiersigilli** [alexiscn/SynologyKit#4]
How I define `options` in the public function `upload`, to work with this public function?
```
var options = UploadOptions(overwrite: true)
        
        client.upload(data: pngdata, filename: filename, destinationFolderPath: destinationFolderPath, createParents: true, options: **options**) { (result) in
```
Now the error is:
`Cannot convert value of type 'UploadOptions' to expected argument type 'SynologyClient.UploadOptions?'`

**Comment by alexiscn** [comment]
Bug fixed. Try 0.2.8.

**Comment by CPiersigilli** [comment]
I tried, but couldn't get it to work.
This this the error.
<img width="606" alt="Schermata 2019-11-17 alle 12 45 17" src="https://user-images.githubusercontent.com/17962752/69007020-77be4c00-0938-11ea-893e-a1fd22580b76.png">

**Comment by CPiersigilli** [comment]
Sorry, I was wrong.
Thank you for the bug fixed.
