### ISSUE TITLE
HELP WANTED - Search File(s) example.

### ISSUE THREAD

**Issue by CPiersigilli** [alexiscn/SynologyKit#5]
To perform tests, in README.md, you could give an example of using:
`client.search(`
with example of `options`, too, for search, for example: `.jpg` and `.jpeg` and `.txt`.

Thank you.

**Comment by alexiscn** [comment]
Bug fixed.

**Comment by CPiersigilli** [comment]
If I use: `searchOptions.pattern = "*.jpg"` work fine.
But, if I use: `searchOptions.pattern = "*.jpg,*.jpeg"` **don't work**.
But, if I use: `searchOptions.extension = "jpg,jpeg"` work fine.
How should I do it?

Thank you.

**Comment by alexiscn** [comment]
> If I use: `searchOptions.pattern = "*.jpg"` work fine.
> But, if I use: `searchOptions.pattern = "*.jpg,*.jpeg"` **don't work**.
> But, if I use: `searchOptions.extension = "jpg,jpeg"` work fine.
> How should I do it?
> 
> Thank you.

I think you should use extension to search with file extension. 

pattern maybe useful for search with names.

**Comment by CPiersigilli** [comment]
> pattern maybe useful for search with names.

Can I use `patterns` with a single name or even with multiple names? If true how is it done? 

Thank you.

**Comment by alexiscn** [comment]
> > pattern maybe useful for search with names.
> 
> Can I use `patterns` with a single name or even with multiple names? If true how is it done?
> 
> Thank you.

You can referer to [official document](https://global.download.synology.com/download/Document/Software/DeveloperGuide/Package/FileStation/All/enu/Synology_File_Station_API_Guide.pdf). I am confused too.

**Comment by CPiersigilli** [comment]
With 0.3.1. work.
Thank you.
