### ISSUE TITLE
Error if I pass wrong `searchPath` in `client.search(atFolderPath: searchPath`

### ISSUE THREAD

**Issue by CPiersigilli** [alexiscn/SynologyKit#6]
If I pass a wrong `searchPath` in `client.search(atFolderPath: searchPath`, I have this error:

<img width="816" alt="Schermata 2019-11-24 alle 18 35 39" src="https://user-images.githubusercontent.com/17962752/69498555-60a7cd00-0ee9-11ea-8ef0-97b08cf571d0.png">

Where am I wrong?

**Comment by alexiscn** [comment]
It's a bug. I will fix it later.

**Comment by CPiersigilli** [comment]
With 0.3.1. work.
Thank you.
