### ISSUE TITLE
HELP WANTED - Function to pass url for use with other tools

### ISSUE THREAD

**Issue by CPiersigilli** [alexiscn/SynologyKit#8]
I want to test your `SynologyKit` with, for example, `SDWebImageSwiftUI`, but I need the `url` to pass to `WebImage(url: URL( `: How can I do?
Can you create a `function`, which given the `path` of the `file`, gives me the complete `url` to download an `image`?
Thank you

**Comment by alexiscn** [comment]
You may take a look at `getThumbOfFile(path:size:completion:) ` function

**Comment by CPiersigilli** [comment]
With `getThumbOfFile(path:size:completion:)` I have `data` of image, not `URL` as `https://www.mydomain.com:5001/webapi/entry.cgi?api=SYNO.FileStation.Download&version=2&method=download&path=/Test/Prova/Immagine_01.jpeg&mode=download`, so I can't use it with other tools as `SDWebImageSwiftUI`

**Comment by CPiersigilli** [comment]
Using `getThumbOfFile(path:size:completion:)` with an incorrect `path` I get this error.
<img width="845" alt="Schermata 2019-12-04 alle 23 14 56" src="https://user-images.githubusercontent.com/17962752/70186455-41c8e800-16ec-11ea-9ed3-801131964ce2.png">

**Comment by CPiersigilli** [comment]
I solved the problem highlighted above as shown below:
```
/// Download di un file contenuto in una cartella, ad esempio "/Test/Prova/Immagine_01.jpeg".
    func downloadFile(filePath:String) {
        client.getThumbOfFile(path: filePath, size: .original) { result in
            switch result {
            case .success(let image):
                if image.count < 200 {
                    if let attributedString = try? NSAttributedString(data: image, options: [.documentType: NSAttributedString.DocumentType.html, .characterEncoding: String.Encoding.utf8.rawValue], documentAttributes: nil) {
                        print("HTML error: \(attributedString)")
                        self.pathFile = ""
                        self.isShowingAlert = true
                        self.error = "HTML error: \(attributedString.string.split(separator: "\n")[0])"
                    }
                } else {
                    self.isShowingAlert = false
                    self.pathFile = filePath
                    self.data = image
                    self.image = UIImage(data: image)!
                }
            case .failure(let error):
                self.isShowingAlert = true
                self.error = "\(error)"
                self.pathFile = ""
                print("error: \(error)")
            }
        }
    }
```
I know it's not a good solution, but I can't do better.
Why doesn't `getThumbOfFile(path:size:completion:)` function have the ability to monitor `progress` variable?
